### ISSUE TITLE
[BUG]: The icon covers the search box

### ISSUE THREAD

**Issue by skyline-123** [zsviczian/excalibrain#105]
<img width="421" alt="image" src="https://user-images.githubusercontent.com/22638687/207859135-3c11885f-bd3b-42c7-9739-8a227c018a61.png">

**Comment by zsviczian** [comment]
Yes... this has been bothering me as well for a while now. It will be fixed when you deploy Excalidraw 1.8.5 (still working on some changes, so not yet sure when I can release - maybe today)

**Comment by skyline-123** [comment]
Fixed.
