### ISSUE TITLE
The line connection between the nodes is very long, making the interface hard to fit in one window

### ISSUE THREAD

**Issue by aaghakhani** [zsviczian/excalibrain#113]
Hi,

The plugin is super amazing, no doubt about it. However, when using the excalibrain in a separate tab, they show up very small, because the line connections are very long and keep the links and nodes far from each other, which leads to a very small font.

**Comment by CarlB01** [comment]
I read your comment and it actually described my issue exactly. So I have made a ‘workaround’ (just some tiny crude changes in my own local /excalibrain/main.js) which seems to fix the problem totally for me - for now, until mr.Zsolt has had time to look into it. I do not use github, i haven’t ‘forked’ the project. But I can read code. So I went for occurences of ‘columnwidth: this.nodeWidth’ and replaced several of them with ‘ columnwidth: this.nodeWidth/2’. Also there was this ‘const childrenCols that i tried to limit to always display three children cols. All these changes would have to be done in the ‘scene.ts’ master file of it was a real project fork. I hope you can follow me. Anyways, I hope it is appropriate to share my private main.js included in this zip provided. Hopefully somebody can make use of it. I really love excalibrain. I think it is such a gem. With the narrowed columns (‘shorter lines’) it did the trick for me.  Love & greetings, Carl B.[unzip and replace ../excalibrain/main.js](https://1drv.ms/u/s!ApYFRPnUGsu2jeFArBA80I1x9oVZkQ?e=OqmOtd)

**Comment by zsviczian** [comment]
I've implemented the change in 0.1.12. Will release soon.
