### ISSUE TITLE
Right-side friends see as inferred

### ISSUE THREAD

**Issue by guix54** [zsviczian/excalibrain#146]
Hello, I do not understand why I can't have a right side view
field <opposition> is in the right side ontology choice (check with ::r)
and I change inferred link color to check what is the link type for [[note5]]
![Capture d’écran 2023-08-02 080551](https://github.com/zsviczian/excalibrain/assets/3319237/0579d88c-ae0a-46f4-a0b4-94923b4fc2cd)

**Comment by zsviczian** [comment]
a node becomes inferred if there are conflicting ontologies added. e.g. node1 refers to node5 as opposite but node5 refers to node1 as source. 
Can you share the contents of node5 as well?
Can you share the screenshot of your ontology configuration in plugin settings?

**Comment by guix54** [comment]
node 5 is empty (is just for my test) as 2/3/4
![Capture d’écran 2023-08-02 100900](https://github.com/zsviczian/excalibrain/assets/3319237/87a03123-cad2-487c-8271-557773a8e3e0)

**Comment by zsviczian** [comment]
I am yet unable to reproduce this issue. Here's the result of my test:

<img width="1675" alt="image" src="https://github.com/zsviczian/excalibrain/assets/14358394/edbcfe76-fa25-41b5-a821-c70882917686">

<img width="1097" alt="image" src="https://github.com/zsviczian/excalibrain/assets/14358394/eb699d01-5b9e-4c24-bf36-5c8c84e8ffd9">

<img width="1083" alt="image" src="https://github.com/zsviczian/excalibrain/assets/14358394/223d7902-444e-4c3b-b92f-3da3718a0a46">

**Comment by guix54** [comment]
Hello, I test in sandbox and all is ok.
after configuration analysis between the 2 vaults, the root cause is"infer all implicit relationships as friends" in my vault this option is toggle on and so right-side friends appears as implicit relationship.
sorry for the inconvenience and thanks for the support

**Comment by zsviczian** [comment]
Thanks! This then is an error in ExcaliBrain. I turned the switch on and this is how my graph looks... but this is not right. 

Will fix this in the next release.

<img width="1680" alt="image" src="https://github.com/zsviczian/excalibrain/assets/14358394/e826a2f0-aa21-4085-9eac-2e215492ca05">

**Comment by zsviczian** [comment]
Thanks again for raising this. I fixed it. I am hoping to release the fix with the next ExcaliBrain update today.

<img width="1679" alt="image" src="https://github.com/zsviczian/excalibrain/assets/14358394/bc3f7f68-88b0-4a54-b8a2-83ba7db63a52">
