### ISSUE TITLE
Startup issues

### ISSUE THREAD

**Issue by zsviczian** [zsviczian/excalibrain#16]
https://twitter.com/catominor3/status/1522663554972897280?s=21&t=1Dpsd9r_1gS7RCCN7nRJEg

**Comment by ciceronianus** [comment]
My Setup: Windows 10
What I did: 
- 1) installed BRAT
- 2) installed ExcaliBrain (and enabled it)
- 3) forgot to install Dataview (and enabled it)
- 4) tried to start ExcaliBrain from the command palette -> Nothing happened.

What I tried afterwards:
- I tried to deactivate different plugins.
- I removed ExcaliBrain and added it again

The JavaScript console does not show more than what I posted on Twitter.

**Comment by zsviczian** [comment]
How large is your vault. ExcaliBrain will not start until Obsidian completes indexing, and then DataView completes indexing. 

Have you tried restarting Excalibrain?

Please try manually deleting `excalibrain.md` from your Vault’s root folder (I am assuming you did not change the default file name). Else try to change the excalibrain file path to something else.

![2E228AFA-B6E9-4A19-A084-0EFBFD357103](https://user-images.githubusercontent.com/14358394/167211893-e3506518-90d6-4044-b64f-dd0ee3ff3e96.jpeg)

**Comment by ciceronianus** [comment]
Issue solved. I created before Excalibrain.md file with info about Excalibrain and that caused the issue.
Deleting the file solved it.

**Comment by zsviczian** [comment]
Thanks. I will add better error handling. e.g. prompting the user to overwrite the file or to set another name or abort the startup.

**Comment by zsviczian** [comment]
resolved in 0.0.5
