### ISSUE TITLE
 Excalibrain doesn't work on my mac because of "TypeError: t.values is not a function"

### ISSUE THREAD

**Issue by benpla** [zsviczian/excalibrain#194]
Excalibrain doesn't work on my mac.

Excalidraw works normal, Excalibrain shows only start page. selected files on other panes or search will be recognized (Footer of Excalibrain drawing), but not showed. The drawing only shows "To get started":
<img width="458" alt="grafik" src="https://github.com/zsviczian/excalibrain/assets/38682514/a67c8c40-8112-44f8-92d9-5ba00215c997">

The Console shows error:
<img width="1087" alt="grafik" src="https://github.com/zsviczian/excalibrain/assets/38682514/eba23103-9dff-4d9b-a1de-d160f7e00607">

Code for Line "3964":
<img width="637" alt="grafik" src="https://github.com/zsviczian/excalibrain/assets/38682514/9df2d23d-897d-4783-b93f-6f456213948f">

## Errors from startup
(1)
The first error after Startup is ExcaliBrain URLParser: Invalid URL https://qisfsv.xxxxxx with "request failed"
 - This is an Intranet URL here
 - URL is sometimes reachable (if I am inside firm VPN) and sometimes not --> normal behaviour

(2)
"Initialized Excalidraw Image Cache"

(3)
"ExcaliBrain indexed 6036 URLs from 1765 unique hosts in 2325 of 3990 markdown files in 6.4 seconds"

(4)
"Uncaught (in promise) TypeError: t.values is not a function"
![grafik](https://github.com/zsviczian/excalibrain/assets/38682514/ee268e6b-71b7-44dc-97eb-e0ee4a6bf75d)

## Versions:
Obsidian Version 1.5.3 (Installer 1.4.13)
ExcaliBrain 0.2.11
ExcaliDraw 2.0.13

**Comment by zsviczian** [comment]
can I ask you to replace your main.js with this one?
[main.zip](https://github.com/zsviczian/excalibrain/files/13818976/main.zip)

Download and unpack the zip
Copy the main.js to Vault/.obsidian/plugins/excalibrain folder
note .obsidian is a hidden folder. 

restart Obsidian and share the results from the console.

**Comment by benpla** [comment]
Thank You for the file. I've replaced the file and this is the console output:
![grafik](https://github.com/zsviczian/excalibrain/assets/38682514/6e7fe72c-5c62-4445-b321-202ae9c41546)

**Comment by zsviczian** [comment]
Let's do a second try. Here's a new main.js: 
[main.zip](https://github.com/zsviczian/excalibrain/files/13820442/main.zip)

On the screenshot please open the toggles as shown:
![image](https://github.com/zsviczian/excalibrain/assets/14358394/70d427bb-2bad-4f92-b38d-2f0fdadc1580)

**Comment by zsviczian** [comment]
This is because you are using a form of properties on the page that I wasn't aware of and seems dataview for those properties works differently. Can you send me the markdown file that is causing the errors? Hopefully based on the detailed log you can figure out which file it might be.

**Comment by zsviczian** [comment]
Thanks. Fixed it. I've also added support for date fields. Will release soon.
