### ISSUE TITLE
Cannot create notes from graph

### ISSUE THREAD

**Issue by nadapez** [zsviczian/excalibrain#201]
When shift-click a node which has no note created yet, a popup appears with three buttons: `Create MD` `Create EX`  and `Nevermind`

The only button clickable is Nevermind. 

The others buttons do nothing

Using Obsidian 1.5.3 with just the neccesary plugins

**Comment by Cmhorn** [comment]
Same experience here. I am on 1.5.3. 

On KDE neon 5.27

**Comment by Cmhorn** [comment]
Quick update. I have tried it again and it works. I think it might be in cases where the node is style modified, the buttons don't function for some reason. I was following the tutorial video on creating Excalibrain from an empty vault. That first time I tried to create an md doc from the node it didn't work. In subsequent instances, it did. 

Hope it helps.

**Comment by zsviczian** [comment]
I fixed the root cause in Excalidraw 2.0.21. Will be released soon. Please reopen if you run into this issue after updating to 2.0.21
