### ISSUE TITLE
about the version check

### ISSUE THREAD

**Issue by Thinkbond** [zsviczian/excalibrain#203]
Every time I check for updates in Obsidian, it prompts me that the Excalibrain plugin needs to be updated. Even after successfully updating to the latest version, when I check for updates again later, Excalibrain still prompts to update from 0.2.11 to 0.2.14.

**Comment by zsviczian** [comment]
ExcaliBrain uses Excalidraw. The prompt to update is from Excalidraw.
If you don't want to regularly update your plugins, you can disable this message in Excalidraw's plugin settings, right at the top under "Basic"

**Comment by Thinkbond** [comment]
No, what I mean is that Excalibrain has already been updated to the latest version, but when I check for updates again, it still prompts that there’s a new version available. And this cycle continues.

**Comment by zsviczian** [comment]
The message you mention comes from Excalidraw. Excalibrain does not prompt such a message. Because ExcaliBrain uses Excalidraw under the hood, you will see the Excalidraw message. You need to update Excalidraw.

If you are using an old version of Obsidian, then it could be that the update is not available because it requires the newer Obsidian API. However, that is unlikely because I only use functions that are at least 1 year old in Obsidian.

**Comment by Thinkbond** [comment]
my version：
obsidian  v1.5.8
Excalidraw 2.0.24 
ExcaliBrain 0.2.14

**Comment by zsviczian** [comment]
hm... I finally understand where you see the update message. In Obsidian's community plugins when clicking check for updates.

I checked the files in GitHub are correct, and also I do not experience the same on my many devices and various test Vaults.

Do you by any chance have multiple devices and some form of sync that overwrites previous updates?

Try deleting the ExcaliBrain plugin and reinstalling.
Before doing so, make sure you make a backup of ExcaliBrain data.json (as it includes all your ExcaliBrain settings including your ontology). You'll find it here Vault/.obsidian/plugins/excalibrain/data.json (note .obsidian is a hidden folder).

After you deleted ExcaliBrain from Community Plugins and reinstalled. Exit Obsidian, replace data.json with the old data.json, and restart Obsidian.

**Comment by Thinkbond** [comment]
I apologize for any inconvenience caused. It was my mistake to realize that the directory name where the plugins are stored did not match the default name. As a result, the version check read from and updated the download directory inconsistently, leading to the update reminder after restarting Obsidian. I apologize for any disruption.
Solution: Delete all folders related to the plugin and reinstall it.
![edc230eb99b66aa270b612a87ec975d](https://github.com/zsviczian/excalibrain/assets/9856020/8276a243-462f-4104-a5c1-88dd406946c2)
