### ISSUE TITLE
Excalibrain disappeared from CMD P options :(

### ISSUE THREAD

**Issue by FEtchevarren** [zsviczian/excalibrain#205]
I have been using Excalibrain for a while and it worked really good. Today it just disappeared from the available options when I hit CMD + P.

The 3 plugins are installed (Excalidraw, DataView and Excalibrain): Excalidraw works perfect, but Excalibrain is missing.

Obsidian version v1.5.11, installer v.1.4.13
Excalibrain version 0.2.14

![image](https://github.com/zsviczian/excalibrain/assets/20057516/47e47a20-48cf-43bf-bc34-eefd4348ed80)

In CMD + P, only this options related to Excali:

![SCR-20240320-ragg](https://github.com/zsviczian/excalibrain/assets/20057516/784f034a-e02f-4c42-b011-8495367a4847)

Don't know if I am doing something wrong :(

**Comment by shoudeyunkaijianyueming** [comment]
me too

**Comment by Dennyyusuf** [comment]
me too

**Comment by zsviczian** [comment]
This is due to a change in the latest Dataview update.  I haven't had time to explore if this is an error on my side in how ExcaliBrain has been using the API or an unintended change on the DV side. I raised an issue, and for now, simply removed the part of the code where I call this feature in DataView.

https://github.com/blacksmithgu/obsidian-dataview/issues/2276

**Comment by GottZ** [comment]
hey there. apparently this was caused by a change in either the compiler or electron.
I don't know exactly why but this fix will solve it when it's pulled into a new release: https://github.com/blacksmithgu/obsidian-dataview/pull/2278/files

**Comment by GottZ** [comment]
new release of dataview has been published. please check if it works now.

**Comment by GottZ** [comment]
it was caused by a change of our compiler target. we changed from es2018 to es2022.
this aparently changed the execution order of the effected code.
