### ISSUE TITLE
[question] It seems don't support YAML Front matter, so this plugin only works with Dataview syntax meta?

### ISSUE THREAD

**Issue by HuangZhuo** [zsviczian/excalibrain#21]

**Comment by zsviczian** [comment]
Not entirely. Front matter aliases and tags are supported. I haven’t checked… does Dataview support front matter data-fields? How would you like to use front matter?

**Comment by HuangZhuo** [comment]
In some old notes, I use the「Breadcrumbs」plugin and set relationship in the Front matter, like:
```
---
alias: Obsidian Plugin
parent: [[Obsidian]]
---
```
So, I think I could see the whole relationship in excalibrain without any changes

**Comment by LawrenceGK** [comment]
Sorry to bother@HuangZhuo, did you find someway to make excalilbrain work with YAML Front matter? For some reason I have to use YAML Front matter to make my dataview DQL work.

**Comment by HuangZhuo** [comment]
> Sorry to bother @HuangZhuo , did you find someway to make excalilbrain work with YAML Front matter? For some reason I have to use YAML Front matter to make my dataview DQL work.

I didn't solve this.
Btw, the 「inline field」syntax seems better than YAML cause the [[file]] link will be treated as a LINK (in Backlinks Panel ). A rename action also works in inline field(but not in YAML).
