### ISSUE TITLE
Gates are out of position

### ISSUE THREAD

**Issue by adrk24** [zsviczian/excalibrain#216]
Obsidian version: 1.6.7 (installer 1.6.3)
Dataview version: 0.5.67
Excalidraw: 2.2.12
Excalibrain: 0.2.15
![image](https://github.com/user-attachments/assets/f265ac50-8047-41c3-bdc7-4ac46aa2ec5f)
Thanks

**Comment by CarlB01** [comment]
+1 on that issue!! 

reproduced in fresh vault + old vault. 
It looks much worse with nodes having many friends/children etc. . 

It appeared after one of the latest obsidian excalidraw (plugin) updates actually!
Which is excalibrain's output engine.

I have struggled for hours with the excalibrain code. I dare not pry into excalidraw.
it **_is_** possible to hack a workaround in `node.ts` under `renderText()` 
- increase the `labelSize.width`, and 
- add `box.width = box.width * 2` at the end.

but the problem ofc goes deeper. 
Has anyone else looked at it? 

Obsidian version: 1.6.7 (installer 1.6.5)
Dataview version: 0.5.67
Excalidraw: 2.3.0
Excalibrain: 0.2.15

**Comment by CarlB01** [comment]
Actually it was fixed in the Obsidian-Excalidraw [2.4.0 Β 3](https://github.com/zsviczian/obsidian-excalidraw-plugin/releases/tag/2.4.0-beta-3) release.
