### ISSUE TITLE
Bottom navigation suggestions

### ISSUE THREAD

**Issue by XuanNui** [zsviczian/excalibrain#22]
1.Can I set a start page that only shows this
HOME/projects/projectA/A-samll project1

2.The folder here is closed, and the folder for navigation is also closed

this is Image 1

Image 2 shows my folder structure
![10](https://user-images.githubusercontent.com/104402409/167327399-f5966396-a98e-450e-b51a-866cb90fcaf5.png)
![11](https://user-images.githubusercontent.com/104402409/167327420-db8ac7a6-b2ef-4b34-b9c9-e086b1341804.png)

**Comment by zsviczian** [comment]
I could add options to hide all pages and only display the folder or tag structure.

**Comment by XuanNui** [comment]
As an example of how to find one of my books on Earth.
Earth / Country / City / Street / Door number / My home / My study / My bookcase / My book
This way you can locate a book, and you can locate anything, i.e. you can locate all the items on the planet.
Assume "Earth/Country/City/Street/Door Number/My House/My Study/My Bookcase/My Book"
Each of these is an obsdian page, and when I open ""door number"", I want to be able to display the earth/country/city/street/door number.
This is also the navigation of notion.


Translated with www.DeepL.com/Translator (free version)

**Comment by zsviczian** [comment]
I added a filter to only display folders (more precisely to not display pages) in 0.0.10.
I will add pins later. For now you can create starred pages in Obsidian and use the starred core plugin to navigate to your favorite starting points in the graph

**Comment by XuanNui** [comment]
Thanks a lot
![QQ截图20220511125955](https://user-images.githubusercontent.com/104402409/167772477-48b752fa-7f27-4d84-961f-14868a3dcb64.png)
