### ISSUE TITLE
The bottom navigational suggestions are displayed slid down if you use Workspaces

### ISSUE THREAD

**Issue by 1001ruchka** [zsviczian/excalibrain#28]
The bottom navigational suggestions are displayed slid down if you use Workspaces.
If you manually run the plugin - bottom navigation suggestions is displayed normally.

https://user-images.githubusercontent.com/5934321/168344968-d51d35ac-442c-411d-9a87-cea8d270d988.mp4

**Comment by zsviczian** [comment]
This was an interesting error. The end solution was in Excalidraw not in ExcaliBrain. Seemingly when you are using workspaces, the workspace is not ready on `app.workspace.onLayoutReady()`.

I will release a fix in Excalidraw 1.6.29 tomorrow.
