### ISSUE TITLE
Question: How do I link to pane? Excalibrain opens a new pane every time when I click the node in excalibrain.

### ISSUE THREAD

**Issue by mzwlevi** [zsviczian/excalibrain#34]
https://user-images.githubusercontent.com/78029539/169510222-40f70cf2-c8bc-4ace-a506-5e4712cc1485.mov

**Comment by zsviczian** [comment]
The button you are click is not the right one. It is the open link button... but it only has a role in Excalidraw Edit mode (based on your misunderstanding I will hide it in view mode).

1) You should go to Excalidraw settings and turn on: `Open in Adjacent Pane`. then you will not have many panes open.
2) Going a step further, if you have multiple panes open, but you want Excalibrain to react only to one pane, you can use the pin button for that. You need to click the pane you want to pin ExcaliBrain to, then you need to click the pin button in ExcaliBrain. After this, ExcaliBrain will only listen to changes in the pinned pane, and when you open pages, it will always open in the pinned pane. Changing the page in other panes will not change the graph in ExcaliBrain.

I hope this video will help you better understand:
https://user-images.githubusercontent.com/14358394/169515560-394dbd6d-5fd5-4e38-9d6b-5a9c495f41d0.mp4

**Comment by mzwlevi** [comment]
> The button you are click is not the right one. It is the open link button... but it only has a role in Excalidraw Edit mode (based on your misunderstanding I will hide it in view mode).
> 
> 1. You should go to Excalidraw settings and turn on: `Open in Adjacent Pane`. then you will not have many panes open.
> 2. Going a step further, if you have multiple panes open, but you want Excalibrain to react only to one pane, you can use the pin button for that. You need to click the pane you want to pin ExcaliBrain to, then you need to click the pin button in ExcaliBrain. After this, ExcaliBrain will only listen to changes in the pinned pane, and when you open pages, it will always open in the pinned pane. Changing the page in other panes will not change the graph in ExcaliBrain.
> 
> I hope this video will help you better understand:
> 
>  2022.05.20.13.00.02.mp4

Thank you!
