### ISSUE TITLE
BUG: Two same setting on command board

### ISSUE THREAD

**Issue by YIRU69** [zsviczian/excalibrain#35]
version : 0.12
![image](https://user-images.githubusercontent.com/48148292/169683174-3b36b3a5-546e-4f01-ab83-ed8e3ad68839.png)

**Comment by zsviczian** [comment]
Interesting.
Does a restart of Obsidian solve the issue?
Can you look into the .obsidian/plugins folder and check what you see? It looks a bit like you have the same plugin but in two different folders (maybe in the past you installed ExcaliBrain manually to a different folder under plugins?
Delete the one that you don't need, but make a backup of the data.json first, so you don't lose your settings.

**Comment by YIRU69** [comment]
I re-install the plugin and restart.
Also delete the data. json.
It also look have any change

**Comment by zsviczian** [comment]
And did the duplication problem get resolved?

**Comment by YIRU69** [comment]
No, it also have the same thing.

**Comment by zsviczian** [comment]
did you ever install excalibrain manually? or always via BRAT?

**Comment by YIRU69** [comment]
@zsviczian install maually.

**Comment by zsviczian** [comment]
My guess is that you have excalibrain installed  two different folders. Please verify in your plugins folder.

**Comment by YIRU69** [comment]
It can't happened when I have two different folders.
Because when I uninstall one excalibrain, I find it disappear on my obsidian plugin.

**Comment by YIRU69** [comment]
![image](https://user-images.githubusercontent.com/48148292/169755255-f4180384-b833-40fa-b5e0-c7df98b67f20.png)

**Comment by YIRU69** [comment]
When I check it today, it look so ...

**Comment by YIRU69** [comment]
I install one excalibrain and have too many excalibrain on the board
![image](https://user-images.githubusercontent.com/48148292/169755474-c201caa2-5dfe-422f-989c-3b17f731f6f6.png)

**Comment by zsviczian** [comment]
Seems this might be caused by some other plugin not ExcaliBrain. I see you have multiple instances of Desmos as well.
Can you try to turn off all your plugins, restart obsidian, then start to turn on plugins 1 by 1. First DataView, next Excalidraw, then ExcaliBrain... to see if the same issue happens?

**Comment by YIRU69** [comment]
@zsviczian  Maybe I find the reason that cause too many excalibrain on my command board.
I use a templater script to start when I restart my obsidian. It can keep so many plugins restart before open obsidian.
```
<%*
fastStart = async (filename, delayInSecond) => {
if (tp.file.exists(filename)) {
const f = tp.file.find_tfile(filename);
let plugins = (await app.vault.read(f)).split(/\r?\n/);
setTimeout(async () => {
plugins.forEach(async (p) => await app.plugins.enablePlugin(p))
}, delayInSecond * 1000)
}
}
await fastStart("FastStart-Plugins-ShortDelay", 2)
await fastStart("FastStart-Plugins-LongDelay", 6)
%>
```

**Comment by YIRU69** [comment]
So if I have to excalibrain in the 'FastStart-Plugins-LongDelay' note, the can start twice.
@zsviczian  Also thank you uncle! It is my mistake.

**Comment by zsviczian** [comment]
In your fast startup script, make sure you activate Excalidraw and Dataview before enabling Excalibrain, else if ExcaliBrain does not detect Dataview and/or Excalidraw it will automatically disable itself. I can imagine that this, combined with your script is leading to the issues.

**Comment by YIRU69** [comment]
yes, thanks for your suggest.
