### ISSUE TITLE
 History Panel: Display alias if available setting

### ISSUE THREAD

**Issue by erichalldev** [zsviczian/excalibrain#42]
The history panel at the bottom of the ExcaliBrain window doesn't respect the setting "Display alias if available". This is a bit jarring since I rely heavily on aliases. I have to switch mental contexts when looking at the graph versus looking at the history list. I would expect the history panel to match the node names in the graph.

![image](https://user-images.githubusercontent.com/5632228/170114578-97e29571-953e-4a07-b110-e7fa16bf70e6.png)

**Comment by zsviczian** [comment]
resolved with #43 
included in 0.0.13
