### ISSUE TITLE
[BUG] Explicitly defined relationships do not support markdown links

### ISSUE THREAD

**Issue by VasylTyshchuk** [zsviczian/excalibrain#50]
"lnfer all implicit relationships as Friend" option is turned on.

Wiki syntax for links work:

![image](https://user-images.githubusercontent.com/71596800/171870009-528adfce-38a8-4681-a90d-e1ed87e4e6d7.png)

Markdown links do not work (the note is on the right side meaning it's friend):

![image](https://user-images.githubusercontent.com/71596800/171869871-2b8eef54-f02b-4f85-952b-e653a9baf51c.png)

**Comment by zsviczian** [comment]
Thanks for raising! I almost exclusively use wiki links, thus I never came across this issue. I will investigate to see what’s going on. From the looks of it, I am guessing that Dataview is not recognizing the link and my fallback processor only checks for wiki links. I am taking a few days off, it will take a couple of days before I can publish a fix.

**Comment by VasylTyshchuk** [comment]
Some apps and one plugin that I use do not support wiki links. I also find the syntax a little more intuitive, and because of that I only use markdown links. Hope it will be implemented soon. Good luck!

**Comment by zsviczian** [comment]
I've implemented this feature. It will be available in 0.0.21
