### ISSUE TITLE
Null on most nodes

### ISSUE THREAD

**Issue by Dennyyusuf** [zsviczian/excalibrain#51]
Hi Zsviczian!

First of all thank you so much for creating this wonderful plugin!
Issue:

After Dataview plugin update to 0.5.24 excalibrain shows most of nodes as null. Not sure what happen here.
<img width="649" alt="image" src="https://user-images.githubusercontent.com/65077044/172033898-63b3c851-e6db-4880-84b3-66f4a652aaa3.png">

Again, thank you so much!
Best,
Denny

**Comment by zsviczian** [comment]
I won't get to look at this until tomorrow. In the mean time, try turning off display of node aliases.

**Comment by zsviczian** [comment]
I fixed some compatibility issues with the new DataView version. Please update to ExcaliBrain 0.0.22 and DataView 0.5.31 and let me know how it goes.
