### ISSUE TITLE
[FR]: add option to show full tag

### ISSUE THREAD

**Issue by meskill** [zsviczian/excalibrain#56]
Currently, for tag with hierarchy e.g.
![image](https://user-images.githubusercontent.com/8974488/173205088-a734aaa7-8d9a-46fd-bbd8-019286ed8c3a.png)

The plugin shows only last part of the tag e.g.
![image](https://user-images.githubusercontent.com/8974488/173205117-34c7ab7e-a88c-4b49-8826-59df7ce6bd75.png)

Consider adding an option to control this behaviour

**Comment by zsviczian** [comment]
This is intentional. You can navigate to #smart and you will see #pointer as its parent. I can make it a setting to display the whole tag path, or just the last section (as currently).

**Comment by meskill** [comment]
Yes, additional setting would be great

**Comment by zsviczian** [comment]
I've implemented this feature in 0.1.1. Hope to release it soon.

**Comment by zsviczian** [comment]
![image](https://user-images.githubusercontent.com/14358394/176884913-e9adb156-8c04-4b70-a60d-8c6d8280f14d.png)
This:
![image](https://user-images.githubusercontent.com/14358394/176884990-6ab03baf-ec88-4133-9da1-83117a8f8309.png)
vs. this:
![image](https://user-images.githubusercontent.com/14358394/176885066-5ae5fba3-6b7d-413f-afa8-b9505cfd37c6.png)
