### ISSUE TITLE
declare relations in YAML using colon   

### ISSUE THREAD

**Issue by trencyclopedia** [zsviczian/excalibrain#57]
Hi, 
Thank you for creating and sharing this nice tool!

Currently we can only specify the relationship in dataview format(::) no matter where we put them. I don't know how difficult it is, but it would be more helpful if it allows to delclare realtions using only one semicolon (instead of dataview format) in YAML like below. 

---
parent: [[dad]], [[mom]]
sibling: [[sister Lara]], [[sister Lara]]
child: [[child Andre]]
---

In this way, it doesn't intefere with the inherent graph view nor affect other plugins(e.g. spaced repetition plugin ) which treat :: as a special mark as well. it will become standalone feature solely for (excalibrain) realtionship management independent from other pulgin functions.

**Comment by trencyclopedia** [comment]
Hi,
Thank you for creating and sharing this nice tool!

Currently we can only specify the relationship in dataview format(::) no matter where we put them. I don't know how difficult it is, but it would be more helpful if it allows to delclare realtions using only one semicolon (instead of dataview format) in YAML like below.

---
parent: [[dad]], [[mom]]
sibling: [[sister Lara]], [[sister Lara]]
child: [[child Andre]]
---

In this way, it doesn't intefere with the inherent graph view nor affect other plugins(e.g. flashcards) which treat :: as a special mark as well. it will become standalone feature solely for (excalibrain) realtionship management independent from other pulgin functions.

**Comment by zsviczian** [comment]
According to this issue: https://github.com/blacksmithgu/obsidian-dataview/issues/1107

the correct format is
`Field: "[[link]]"` and `Field: ["[[link1]]", "[[link2]]"]`

I tested this, and this works without issues with the current version of ExcaliBrain.

**Comment by trencyclopedia** [comment]
thank you very much for your prompt reply and the clarification! 

I can confirm now that this format `field: ["[[link1]]", "[[link2]]"]` indeed works, though they are recognized as plain text instead of links, as you mentioned. This format is not very handy to create and manage references either. 

I am not familiar with the specification of YAML format. I don't know if this is the only/standard way to declare it, but it would be much appreciated if someone could come up with some easiler ways to create multiple links. 

I tried these format ` field: [[link1]] [[link2]]` , ` field: [[link1], [link2]]` which both works for exclibrain, but they coflict with the spaced repetition plugin. I might have to ask its developer.
