### ISSUE TITLE
“Brain Graph Off” when switch workspace

### ISSUE THREAD

**Issue by Steven-AA** [zsviczian/excalibrain#58]
![sp20220615_112849_263](https://user-images.githubusercontent.com/22387129/173731295-b2c0e5f3-a948-4afa-bb7a-e50acbd2236d.png)

Brain graph shows the note  the same as I save the workspace, won't change when I click on another note.

I remember there was a "Brain Graph On" command in the earlier version, cannot find it now.

![sp20220615_113653_857](https://user-images.githubusercontent.com/22387129/173731728-c55f2a51-7738-414d-92e0-006809055580.png)

plugins:

- Workspaces Plus 0.3.1
- Excalidraw 1.6.33
- ExcaliBrain 0.0.22
- Key Promoter 1.2.2 ( which shows the “Brain Graph Off” command.

**Comment by Steven-AA** [comment]
but "ExcaliBrain Normal" will not refresh or open Brain Graph for me.

**Comment by Steven-AA** [comment]
It seems fixed after updating Obsidian to v0.15.1.
Switch workspace will turn Brain Graph on/off, bug?
"ExcaliBrain Normal" now works.

**Comment by zsviczian** [comment]
Obsidian 0.15.1 brings some very significant changes to the underlying Obsidain environment. As of right now, I am not sure how/if I will be able to address them all. WIP, but will take lots of effort/time to figure out how/what to do.

**Comment by Steven-AA** [comment]
The problem disappeared in Obsidian v0.15.2.
Now Brain Graph will turn off and then auto turn on when I switch the workspace.
![sp20220618_212010_082](https://user-images.githubusercontent.com/22387129/174439597-1c8dcd32-3360-4c92-8f97-77bef86c0711.png)

**Comment by zsviczian** [comment]
great!
