### ISSUE TITLE
All relationships are inferred only

### ISSUE THREAD

**Issue by cashew90** [zsviczian/excalibrain#62]
Hi,

I am experiencing a weird issue where all relationship only appear as inferred, albeit clearly being defined. Do you have any idea why this occurs and what to do about? Thank you! (I love Excalibrain, btw.).

Example:

1) I set up a parent-child relationship in the child note.

<img width="953" alt="CleanShot 2022-06-16 at 17 33 17@2x" src="https://user-images.githubusercontent.com/20352339/174106726-da9e06d9-ff29-4e7f-bdcc-7e5e8179f1af.png">

2) And just to be safe also in the parent note

<img width="803" alt="CleanShot 2022-06-16 at 17 34 20@2x" src="https://user-images.githubusercontent.com/20352339/174106904-44771734-f18f-4065-a82a-50ce4d6d8621.png">

3) Strangly however, it is shown as inferred only and will disappear when toggling 'Show inferred notes' to off.  🤷‍♂️

<img width="1038" alt="CleanShot 2022-06-16 at 17 35 35@2x" src="https://user-images.githubusercontent.com/20352339/174107250-1dfe6d8d-36a1-4da3-86a9-d0ebc790192b.png">

**Comment by zsviczian** [comment]
Did you recently install the Dataview update? Restart Obsidian wait a few minutes and hopefully ExcaliBrain will be back to normal

**Comment by zsviczian** [comment]
I should have read your issue more carefully, sorry. 
Dataview frontmatter link support changed. According to this issue: https://github.com/blacksmithgu/obsidian-dataview/issues/1107

the correct format is
`Field: "[[link]]"` and `Field: ["[[link1]]", "[[link2]]"]`

I tested this, and this works without issues with the current version of ExcaliBrain.

**Comment by cashew90** [comment]
Can confirm this fixed it. Thank you!
