### ISSUE TITLE
how to exclude folder from showing in excalibrain?

### ISSUE THREAD

**Issue by Oratoriooooo** [zsviczian/excalibrain#63]
version 0.0.22
I see there is a field under Display-filepath to exclude, where I can put path in, but it is not working.
for example, I want to exclude daily note from D:\Obsidian Vault\002 Utility\Daily Commit
I tried: 
1. D:\Obsidian Vault\002 Utility\Daily Commit
2. Obsidian Vault\002 Utility\Daily Commit
3. 002 Utility\Daily Commit
None of them works.
Thanks.

**Comment by zsviczian** [comment]
`002 Utility/Daily Commit` should work. Note / instead of \
