### ISSUE TITLE
[Bug]Duplicate "tag-tree"

### ISSUE THREAD

**Issue by kazdonkai** [zsviczian/excalibrain#74]
As shown in the image, multiple "tag-trees" of edge text are displayed.
<img width="697" alt="スクリーンショット 2022-07-19 13 06 41" src="https://user-images.githubusercontent.com/90127278/179663200-699c5a8b-2643-4b5e-92e0-8ed5b74cf5df.png">

**Comment by zsviczian** [comment]
Fixed this in 0.1.5. Will release the fix in 1-2 days.
