### ISSUE TITLE
[FR] Reverse the logic in links and backlinks

### ISSUE THREAD

**Issue by MSus4** [zsviczian/excalibrain#78]
Possibility to "reverse" the logic when it comes to links and backlinks would be great. My vault is structured in a way that forward link should be inferred as a parent and backlink as a child.

**Background:**
when I make a new note, I first create an empty note, name it and write down the idea. Only after that I think where should I link it. Then I make the link(s) to another note(s). And logically, I most of the time connect the note to something larger topic. 
Before ExcaliBrain I have used option "show backlinks in document", and that way "Topic Notes" have a backlink list of their subtopics. 

I do realize that some people go to the "Topic Note" and make a wikilink first, then click the link to actually _make_ the note. That way current logic to infer connections in Excalibrain is valid. But I hope that an option to reverse this logic would be implemented, so that it fits the other workflow also.

**Comment by zsviczian** [comment]
I've implemented this feature in 0.1.5. There are a few other enhancements I am planning to make. I will probably release 0.1.5 tomorrow.

**Comment by MSus4** [comment]
> I've implemented this feature in 0.1.5. There are a few other enhancements I am planning to make. I will probably release 0.1.5 tomorrow.

Great! Thanks! 🥳
