### ISSUE TITLE
Some nodes/notes are showing as 'null'

### ISSUE THREAD

**Issue by SunnyOd** [zsviczian/excalibrain#83]
Hi,

Firstly just want to say thank you for making such an inspired and immensely transformative plugin. I've been struggling to make use of the official graph and was hoping something like this would be created and you've done it and done it beyond anything I'd hoped for. Looking forward to using it more!

The issue I'm having, as title states, is that *some* of the notes/nodes on the drawing appear with title 'null'. I've looked at the contents of the notes and there is nothing I can tell in common between them and I'm not sure how to debug this. This is an example:

![image](https://user-images.githubusercontent.com/10949821/185003083-b3866a49-b4d0-46d8-a7d3-49ec08137f48.png)
 
If I hover over the node I can see the correct file/path and clicking it opens it correctly. So looks like it's just not rendering the filename for some reason. Could it be a setting or maybe another plugin that i'm running (there are a few).  I can get more info across, just let me know what's required?

Thanks
Sunny

**Comment by zsviczian** [comment]
Are you using the `Javascript for rendering node names` feature by any chance? 
If yes, that could be the source of the problem. 

But in any case you could start debugging by adding the following script and then checking in developer console the output.
`(!defaultName?console.log(dvPage):"")||defaultName`

![image](https://user-images.githubusercontent.com/14358394/185044308-8b127fce-f373-4dc1-9257-04d5e9771963.png)

**Comment by SunnyOd** [comment]
Hi Zsviczian,

Thanks for getting back to me

The `Javascript for rendering node names` field was blank. I applied the debugging script and this is the output I got in the console immediately afterwards:

![image](https://user-images.githubusercontent.com/10949821/185098101-13208a9a-3de2-443d-a7ea-5e10412e1717.png)

I saw 'graph_analysis' plugin could be causing issues so I uninstalled it and restarted obsidian. I'm still getting some 'null' notes but the console shows this:

![image](https://user-images.githubusercontent.com/10949821/185099922-4ed0b24d-6e67-48cb-bd6f-70cebfc728e2.png)

**Comment by zsviczian** [comment]
Hm... its interesting why adding the debug code to ExcaliBrain would have tripped the graph analysis plugin.
The second screenshot of the developer console is after navigating with ExcaliBrain and seeing couple of `null`s?
If not, then please navigate in ExcaliBrain until you come across a null, and then make a screenshot of developer console. 
If yes, then we may need to tweak the debug script... try this `console.log(defaultName,dvPage)||defaultName`

The result of the second script should look something like this on developer console.
Try to locate the file causing the `null` and expand the dataview object as you can see on the screenshot... and make a screenshot. Perhaps we'll learn something.

![image](https://user-images.githubusercontent.com/14358394/185111756-50dcbce6-ed97-47d4-8afe-503c2a3b6fae.png)

**Comment by SunnyOd** [comment]
Yeah that's right the screenshot was taken after a couple of different pages were loaded which had nulls on them... 

I just updated the debug and this is the result after nulls showed up:

![image](https://user-images.githubusercontent.com/10949821/185143918-b904a492-647a-45d6-a095-5bc44c4b2538.png)

I'm learning some cools stuff here - thanks!

**Comment by zsviczian** [comment]
Can you right click on one of the `{file: ...` sections, where you see null at the beginning of the row, and that is not confidential, and select "copy object" and paste the result in a response here?
It will be a pretty long JSON string.

![image](https://user-images.githubusercontent.com/14358394/185152166-70224c8a-4388-4e31-a2ea-b350606b0d66.png)

**Comment by SunnyOd** [comment]
Sure...
{
    "file": {
        "path": "5 Areas/Computing/DevOps/DevOps Basics.md",
        "folder": "5 Areas/Computing/DevOps",
        "name": "DevOps Basics",
        "link": {
            "path": "5 Areas/Computing/DevOps/DevOps Basics.md",
            "embed": false,
            "type": "file"
        },
        "outlinks": {
            "values": [
                {
                    "path": "5 Areas/Computing/DevOps/DevOps Basics.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/What is DevOps - Really Understand it.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/What is DevOps.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/DevOps Learning Process.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/How to Become a DevOps Engineer - Roadmap 2022.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/DevOps MOC.md",
                    "embed": false,
                    "type": "file"
                }
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 6
        },
        "inlinks": {
            "values": [
                {
                    "path": "excalibrain.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/What is DevOps.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/How to Become a DevOps Engineer - Roadmap 2022.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/DevOps MOC.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "5 Areas/Computing/DevOps/DevOps Basics.md",
                    "embed": false,
                    "type": "file"
                }
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 5
        },
        "etags": {
            "values": [
                "#🧠/🔽i/youtube▶️/🟧",
                "#🗃️/📄n/3MOC",
                "#🗃️/🌳s/1Seeds🌰"
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 3
        },
        "tags": {
            "values": [
                "#🧠/🔽i/youtube▶️/🟧",
                "#🧠/🔽i/youtube▶️",
                "#🧠/🔽i",
                "#🧠",
                "#🗃️/📄n/3MOC",
                "#🗃️/📄n",
                "#🗃️",
                "#🗃️/🌳s/1Seeds🌰",
                "#🗃️/🌳s"
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 9
        },
        "aliases": {
            "values": [
                "null"
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 1
        },
        "lists": {
            "values": [],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 0
        },
        "tasks": {
            "values": [],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 0
        },
        "ctime": "2022-08-16T16:22:19.572+01:00",
        "cday": "2022-08-16T00:00:00.000+01:00",
        "mtime": "2022-08-16T16:44:31.522+01:00",
        "mday": "2022-08-16T00:00:00.000+01:00",
        "size": 487,
        "starred": false,
        "frontmatter": {
            "created": "2022-08-16T16:22",
            "tags": [
                " #🗃️/📄n/3MOC #🗃️/🌳s/1Seeds🌰 "
            ],
            "aliases": [
                null
            ]
        },
        "ext": "md"
    },
    "created": "2022-08-16T16:22:00.000+01:00",
    "tags": [
        " #🗃️/📄n/3MOC #🗃️/🌳s/1Seeds🌰 "
    ],
    "aliases": [
        null
    ],
    "Tags": "` #🧠/🔽i/youtube▶️/🟧",
    "Context": "`",
    "Up": "` [[DevOps MOC|DevOps]]",
    "Side": "`",
    "Next": "`",
    "Prev": "`",
    "Down": "`",
    "External": "`",
    "context": "`",
    "up": "` [[DevOps MOC|DevOps]]",
    "side": "`",
    "next": "`",
    "prev": "`",
    "down": "`",
    "external": "`"
}

**Comment by SunnyOd** [comment]
Sure, this was from a row that started with null:

{
    "file": {
        "path": "4 Brain/Social Order.md",
        "folder": "4 Brain",
        "name": "Social Order",
        "link": {
            "path": "4 Brain/Social Order.md",
            "embed": false,
            "type": "file"
        },
        "outlinks": {
            "values": [
                {
                    "path": "5 Areas/Maya/Sociology.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "3 Sources/Content/Youtube/+ Elon Musk Offers to Buy Twitter (Dr Steve Turley).md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "4 Brain/Social Order.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "4 Brain/Mass Society.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "4 Brain/Network Society.md",
                    "embed": false,
                    "type": "file"
                }
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 5
        },
        "inlinks": {
            "values": [
                {
                    "path": "4 Brain/Social Order.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "4 Brain/Network Society.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "4 Brain/Mass Society.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "4 Brain/Big Media.md",
                    "embed": false,
                    "type": "file"
                },
                {
                    "path": "3 Sources/Content/Youtube/+ Elon Musk Offers to Buy Twitter (Dr Steve Turley).md",
                    "embed": false,
                    "type": "file"
                }
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 5
        },
        "etags": {
            "values": [
                "#🗃️/📄n/zettel🐾",
                "#🗃️/🌳s/1Seeds🌰"
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 2
        },
        "tags": {
            "values": [
                "#🗃️/📄n/zettel🐾",
                "#🗃️/📄n",
                "#🗃️",
                "#🗃️/🌳s/1Seeds🌰",
                "#🗃️/🌳s"
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 5
        },
        "aliases": {
            "values": [
                "null"
            ],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 1
        },
        "lists": {
            "values": [],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 0
        },
        "tasks": {
            "values": [],
            "settings": {
                "renderNullAs": "\\-",
                "taskCompletionTracking": false,
                "taskCompletionText": "completion",
                "warnOnEmptyResult": true,
                "refreshEnabled": true,
                "refreshInterval": 250,
                "defaultDateFormat": "yyyy-MM-dd",
                "defaultDateTimeFormat": "\"yyyy-MM-dd'T'HH:mm\"  ",
                "maxRecursiveRenderDepth": 6,
                "tableIdColumnName": "File",
                "tableGroupColumnName": "Group",
                "allowHtml": true,
                "inlineQueryPrefix": "=",
                "inlineJsQueryPrefix": "$=",
                "inlineQueriesInCodeblocks": true,
                "enableDataviewJs": true,
                "enableInlineDataviewJs": true,
                "prettyRenderInlineFields": true,
                "taskLinkLocation": "end",
                "taskLinkText": "🔗",
                "schemaVersion": 1
            },
            "length": 0
        },
        "ctime": "1970-01-01T01:00:00.000+01:00",
        "cday": "1970-01-01T00:00:00.000+01:00",
        "mtime": "2022-05-12T23:44:10.626+01:00",
        "mday": "2022-05-12T00:00:00.000+01:00",
        "size": 428,
        "starred": false,
        "frontmatter": {
            "created": "2022-04-17T18:22",
            "tags": [
                " #🗃️/📄n/zettel🐾 #🗃️/🌳s/1Seeds🌰  "
            ],
            "aliases": [
                null
            ]
        },
        "ext": "md"
    },
    "created": "2022-04-17T18:22:00.000+01:00",
    "tags": [
        " #🗃️/📄n/zettel🐾 #🗃️/🌳s/1Seeds🌰  "
    ],
    "aliases": [
        null
    ],
    "up": {
        "path": "5 Areas/Maya/Sociology.md",
        "type": "file",
        "embed": false
    },
    "refs": {
        "path": "3 Sources/Content/Youtube/+ Elon Musk Offers to Buy Twitter (Dr Steve Turley).md",
        "type": "file",
        "embed": false
    },
    "Tags": "`",
    "Context": "`",
    "Up": "` [[Sociology]]",
    "Side": "`",
    "Next": "`",
    "Prev": "`",
    "Down": "`",
    "External": "`",
    "context": "`",
    "side": "`",
    "next": "`",
    "prev": "`",
    "down": "`",
    "external": "`"
}

**Comment by zsviczian** [comment]
Do you have an aliases field on the front matter of this page? Is it empty?
It seems DataView is translating the empty alias field to "null" and not to `[]`.

This is what I see in the JSON you sent:
```json
{
  "aliases": {
    "values": [
      "null"
    ],
}
```

and this is what I would have expected to see if the alias is empty
```json
{
  "aliases": {
    "values": [],
}
```

try turning off `Display alias if available` in settings.

**Comment by SunnyOd** [comment]
I have an aliases field and it's empty...
![image](https://user-images.githubusercontent.com/10949821/185207729-ee72ffc8-7702-43bf-8c95-3337cbfdc3ec.png)

"try turning off Display alias if available in settings."
YEP - That's fixed it!!

Gonna be putting ExcaliBrain to good use over the next few weeks. Very excited

Thank You, Zsviczian :smile_cat: 
Sunny
