### ISSUE TITLE
Proliferation of panes

### ISSUE THREAD

**Issue by axelson** [zsviczian/excalibrain#85]
First off, thanks for Excalibrain! I love the visual way of seeing the relationships between my notes.

I appear to have some setting incorrect, because when I use excalibrain to navigate, every click is opening up a new pane which means if I explore my notes in excalibrain I quickly begin to become overwhelmed with the number of new panes:

https://user-images.githubusercontent.com/9973/185805783-70543a40-8f4c-4afa-a29f-a6e22198eadd.mp4

Is there a way to tell excalibrain to open the clicked note in an already existing pane instead of opening a new pane? I didn't see anything in the excalibrain settings and control/shift/alt didn't seem to make a difference.

**Comment by zsviczian** [comment]
yes - that is a bit more complex than should be...
see the solution here: https://github.com/zsviczian/excalibrain/issues/34
you need to enable open in adjacent panes in the Excalidraw plugin settings.

**Comment by axelson** [comment]
Thanks! That works for me (although I wouldn't have thought to look at the Excalidraw settings for this). Here's what I ended up going with:

![Screen Shot 2022-08-21 01-56-54](https://user-images.githubusercontent.com/9973/185816674-74b69674-74a2-428e-a810-d26628f85482.png)

**Comment by zsviczian** [comment]
> although I wouldn't have thought to look at the Excalidraw settings for this

this is what I meant by "bit more complex than should be"

**Comment by toddz262** [comment]
I have to imagine @axelson and I are not the only ones to object to the default behavior. I probably haven't explored all the videos and documentation of Excalibrain, but so far I had not seen any mention of how to make this change. It seems like an instruction that should be made pretty visible to new users.
