### ISSUE TITLE
Randomly not working

### ISSUE THREAD

**Issue by keape** [zsviczian/excalibrain#86]
I just reinstalled this plugin which seems very promising but randomly, in some notes, is not working.
I have to toggle the buttons on top several times and (maybe) the diagrams appear. In some other cases the problem is not fixing and the only thing I see is the blue background. 

Any idea? Maybe plugin conflicts?

I upload an image from one of the notes which is not working.

Thank you
![Screenshot 2022-08-23 180701](https://user-images.githubusercontent.com/59424846/186207637-00c54a8e-4649-4e33-9baf-042b6300ca44.png)
!

**Comment by zsviczian** [comment]
I just ran into the same issue myself. I am not looking for the root cause.

**Comment by zsviczian** [comment]
seems as if there has been a change to dataview.

**Comment by zsviczian** [comment]
I just released the fix 0.1.10
