### ISSUE TITLE
Request: no automatic focus on search field after opening Excalibrain

### ISSUE THREAD

**Issue by koenbunders** [zsviczian/excalibrain#87]
Open a note in one pane. Open Excalibrain normal. Excalibrain opens in a second pane for the selected note in the first pane. As expected. Yet, the search field is automatically activated and therefor a large dropdown is displayed (and an additional click is needed to make it disappear).

Request: prevent focus on search field when excalibrain is opened (or even better: make it optional).

**Comment by zsviczian** [comment]
implemented in 0.1.11
