### ISSUE TITLE
Request: no auto resize

### ISSUE THREAD

**Issue by koenbunders** [zsviczian/excalibrain#88]
Open a note in one pane. Open Excalibrain normal. Excalibrain opens in a second pane for the selected note in the first pane.  Click on another link in the text of the note in the first pane. The excalibrain view in the second pane refreshes, now displaying for the selected note in the first pane. As expected. Yet, excalibrain resizes automatically. Fonts get bigger with less links, fonts get smaller with many links. 

Request: prevent auto-resize (or even better: make it optional). This would make using excalibrain so much more pleasant.

**Comment by zsviczian** [comment]
Added to 0.1.11 (yet to be released).
