### ISSUE TITLE
Nodes unresponsive at smaller window sizes

### ISSUE THREAD

**Issue by danlandrum** [zsviczian/excalibrain#9]
The nodes don't navigate properly unless the window size is large enough to display the zoom buttons.

**Comment by zsviczian** [comment]
I also noticed the issue with links not working at smaller sizes, but did not spot the correlation with the zoom buttons. This gives me a hint as to where to search for a solution.

**Comment by 1001ruchka** [comment]
> I also noticed the issue with links not working at smaller sizes
Yes on the Macbook Pro 13 (1280x800) the zoom buttons are not displayed and clicking on a note takes 2-4 tries.

**Comment by zsviczian** [comment]
I've investigated this issue a bit. Based on my current understanding, this seems like an undesired side effect of how Excalidraw implemented the Mobile view. I will need to debug Excalidraw to fix this. I hope to do it in the coming days. Once the Excalidraw fix is released, I will deploy the change to Obsidian-Excalidraw... and finally it will trickle down to Excalibrain as well.

**Comment by zsviczian** [comment]
fixed in 0.0.5, will release it later today, however, you will also need to update Excalidraw to 1.6.28
