### ISSUE TITLE
disable ctrl+click on image - it closes my document and opens an image instead

### ISSUE THREAD

**Issue by 7flash** [zsviczian/excalibrain#90]

**Comment by 7flash** [comment]
It happens to me often when my actual intention different i.e. selecting multiple elements with ctrl+click

**Comment by 7flash** [comment]
Found solution in Settings:

![image](https://user-images.githubusercontent.com/4569866/187922584-2c4193dd-b81d-40c7-99cd-f8b6b9f6612c.png)

![image](https://user-images.githubusercontent.com/4569866/187922611-a7bc758d-a8af-42b6-b3ca-1e00a01d4fa3.png)

![image](https://user-images.githubusercontent.com/4569866/187922628-67de55fe-d0da-46e5-b3ff-00c246a21735.png)

**Comment by zsviczian** [comment]
and has this setting solved your issue?
