### ISSUE TITLE
Cannot get graph to show edge labels

### ISSUE THREAD

**Issue by xdhrvt** [zsviczian/excalibrain#98]
Hi - congrats for your great work ! 

I am probably stupid but I cannot find how to get the edge labels (as per Ontology) displayed in Excalibrain...

It appears in some of your videos but I cannot find the how to.

Help appreciated - Thx

**Comment by xdhrvt** [comment]
I was stupid indeed ! found it...

**Comment by max-nothacker** [comment]
Can you share where you found it? I have the same issue.
